import { useState } from "react";

import {
    ActivityIndicator,
    Alert,
    Platform,
    SafeAreaView,
    ScrollView,
    StyleSheet,
    Text,
    TouchableOpacity,
    View,
} from "react-native";

import {
    Camera,
    CameraView,
    useCameraPermissions,
} from "expo-camera";

import * as ImagePicker from "expo-image-picker";

import {
    deductFromWallet,
    getWalletBalance,
    saveWalletBalance,
} from "../storage/walletStorage";

import {
    getSavedBills,
    saveBill,
} from "../storage/billStorage";

function ScanScreen({ navigation }) {

    const [permission, requestPermission] =
        useCameraPermissions();

    const [showCamera, setShowCamera] =
        useState(false);

    const [isScanning, setIsScanning] =
        useState(false);

    const [isLoadingPayment, setIsLoadingPayment] =
        useState(false);

    const [isPaying, setIsPaying] =
        useState(false);

    const [paymentData, setPaymentData] =
        useState(null);

    const [backendUrl, setBackendUrl] =
        useState("");

    const showMessage = (title, message) => {

        if (Platform.OS === "web") {
            window.alert(`${title}\n\n${message}`);
            return;
        }

        Alert.alert(title, message);
    };

    const formatMoney = (amount) =>
        Number(amount || 0).toFixed(2);

    const validateQR = (rawQR) => {

        let qr;

        try {
            qr = JSON.parse(rawQR);
        } catch {
            throw new Error(
                "Invalid BillPay QR."
            );
        }

        if (
            qr.type !==
            "BILLPAY_BACKEND_PAYMENT"
        ) {
            throw new Error(
                "This QR was not generated by BillPay."
            );
        }

        if (!qr.paymentId) {
            throw new Error(
                "Payment ID missing."
            );
        }

        if (!qr.apiUrl) {
            throw new Error(
                "Backend URL missing."
            );
        }

        return qr;
    };

    const fetchPaymentFromBackend = async (
        qr
    ) => {

        setIsLoadingPayment(true);

        try {

            const url =
                qr.apiUrl.replace(/\/$/, "");

            const response =
                await fetch(
                    `${url}/api/payments/${qr.paymentId}`
                );

            const result =
                await response.json();

            if (!response.ok) {
                throw new Error(
                    result.message
                );
            }

            if (
                result.status ===
                "EXPIRED"
            ) {
                throw new Error(
                    "This payment QR has expired."
                );
            }

            if (
                result.status ===
                "PAID"
            ) {
                throw new Error(
                    "Invoice already paid."
                );
            }

            setBackendUrl(url);

            setPaymentData(result);

            setShowCamera(false);

        } catch (err) {

            console.log(err);

            showMessage(
                "Unable to load payment",
                err.message
            );

        } finally {

            setIsLoadingPayment(false);

            setIsScanning(false);

        }

    };

    const processQR = async (
        rawQR
    ) => {

        try {

            const qr =
                validateQR(rawQR);

            await fetchPaymentFromBackend(
                qr
            );

        } catch (err) {

            showMessage(
                "QR Error",
                err.message
            );

        }

    };

    const handleBarcodeScanned = ({
        data,
    }) => {

        if (isScanning) return;

        setIsScanning(true);

        processQR(data);

    };

    const openCamera = async () => {

        if (!permission.granted) {

            const result =
                await requestPermission();

            if (!result.granted) {

                showMessage(
                    "Permission Required",
                    "Allow camera permission."
                );

                return;

            }

        }

        setShowCamera(true);

        setPaymentData(null);

    };

    const uploadQRImage = async () => {

        try {

            const permission =
                await ImagePicker.requestMediaLibraryPermissionsAsync();

            if (!permission.granted) {

                showMessage(
                    "Permission Required",
                    "Gallery permission denied."
                );

                return;

            }

            const image =
                await ImagePicker.launchImageLibraryAsync({

                    mediaTypes: ["images"],

                    quality: 1,

                });

            if (image.canceled)
                return;

            setIsLoadingPayment(true);

            const qr =
                await Camera.scanFromURLAsync(
                    image.assets[0].uri,
                    ["qr"]
                );

            if (!qr.length) {

                showMessage(
                    "No QR",
                    "No QR found in image."
                );

                return;

            }

            await processQR(
                qr[0].data
            );

        } catch (err) {

            console.log(err);

            showMessage(
                "Upload Failed",
                err.message
            );

        } finally {

            setIsLoadingPayment(false);

        }

    };

    const confirmPayment = () => {

        if (!paymentData)
            return;

        const ok =
            Platform.OS === "web"
                ? window.confirm(
                      `Pay ₹${formatMoney(
                          paymentData.amount
                      )} to ${
                          paymentData.merchant
                              .merchantName
                      }?`
                  )
                : true;

        if (ok) {

            completePayment();

        }

    };

    const completePayment =
        async () => {

            let balanceBefore = 0;

            let deducted = false;

            try {

                const bills =
                    await getSavedBills();

                if (
                    bills.some(
                        (bill) =>
                            bill.payment
                                .paymentId ===
                            paymentData.paymentId
                    )
                ) {

                    throw new Error(
                        "Already paid."
                    );

                }

                balanceBefore =
                    await getWalletBalance();

                if (
                    balanceBefore <
                    paymentData.amount
                ) {

                    throw new Error(
                        "Insufficient balance."
                    );

                }

                await deductFromWallet(
                    paymentData.amount
                );

                deducted = true;
                                const mobileReference =
                    `MOBILE-${Date.now()}`;

                const response = await fetch(
                    `${backendUrl}/api/payments/${paymentData.paymentId}/pay`,
                    {
                        method: "POST",

                        headers: {
                            "Content-Type":
                                "application/json",
                        },

                        body: JSON.stringify({
                            amount: Number(
                                paymentData.amount
                            ),

                            mobileReference,
                        }),
                    }
                );

                const responseText =
                    await response.text();

                let result;

                try {
                    result =
                        JSON.parse(
                            responseText
                        );
                } catch {
                    throw new Error(
                        "The backend returned an invalid response."
                    );
                }

                if (!response.ok) {
                    throw new Error(
                        result.message ||
                            "Payment was rejected by the backend."
                    );
                }

                if (!result.payment) {
                    throw new Error(
                        "Paid invoice data was not returned."
                    );
                }

                const paidPayment =
                    result.payment;

                const savedInvoice = {
                    version: 1,

                    type:
                        "BILLPAY_PAID_INVOICE",

                    payment: {
                        paymentId:
                            paidPayment.paymentId,

                        amount: Number(
                            paidPayment.amount
                        ),

                        currency:
                            paidPayment.currency ||
                            "INR",

                        status:
                            paidPayment.status,

                        createdAt:
                            paidPayment.createdAt,

                        expiresAt:
                            paidPayment.expiresAt,

                        paidAt:
                            paidPayment.paidAt,

                        mobileReference:
                            paidPayment.mobileReference,
                    },

                    merchant: {
                        merchantId:
                            paidPayment.merchant
                                ?.merchantId,

                        merchantName:
                            paidPayment.merchant
                                ?.merchantName,

                        place:
                            paidPayment.merchant
                                ?.place,

                        phone1:
                            paidPayment.merchant
                                ?.phone1,

                        phone2:
                            paidPayment.merchant
                                ?.phone2,

                        email:
                            paidPayment.merchant
                                ?.email,

                        gstin:
                            paidPayment.merchant
                                ?.gstin,
                    },

                    customer: {
                        customerName:
                            paidPayment.customer
                                ?.customerName,

                        phoneNumber:
                            paidPayment.customer
                                ?.phoneNumber,
                    },

                    invoice: {
                        invoiceNumber:
                            paidPayment.invoice
                                .invoiceNumber,

                        invoiceDate:
                            paidPayment.invoice
                                .invoiceDate,

                        company:
                            paidPayment.invoice
                                .company,

                        customer:
                            paidPayment.invoice
                                .customer,

                        products:
                            paidPayment.invoice.products.map(
                                (product) => ({
                                    serialNumber:
                                        Number(
                                            product.serialNumber
                                        ),

                                    productName:
                                        product.productName,

                                    quantity:
                                        Number(
                                            product.quantity
                                        ),

                                    rate:
                                        Number(
                                            product.rate
                                        ),

                                    netAmount:
                                        Number(
                                            product.netAmount
                                        ),

                                    gstPercentage:
                                        Number(
                                            product.gstPercentage
                                        ),

                                    gstAmount:
                                        Number(
                                            product.gstAmount
                                        ),

                                    total:
                                        Number(
                                            product.total
                                        ),
                                })
                            ),

                        totals: {
                            totalAmountBeforeTax:
                                Number(
                                    paidPayment
                                        .invoice
                                        .totals
                                        .totalAmountBeforeTax
                                ),

                            totalGSTAmount:
                                Number(
                                    paidPayment
                                        .invoice
                                        .totals
                                        .totalGSTAmount
                                ),

                            grossTotal:
                                Number(
                                    paidPayment
                                        .invoice
                                        .totals
                                        .grossTotal
                                ),

                            roundOffAmount:
                                Number(
                                    paidPayment
                                        .invoice
                                        .totals
                                        .roundOffAmount
                                ),

                            receivableAmount:
                                Number(
                                    paidPayment
                                        .invoice
                                        .totals
                                        .receivableAmount
                                ),
                        },

                        paymentMethod:
                            paidPayment.invoice
                                .paymentMethod ||
                            "UPI",
                    },

                    localReceipt: {
                        verified: true,

                        storedAt:
                            new Date().toISOString(),
                    },
                };

                await saveBill(
                    savedInvoice
                );

                const remainingBalance =
                    balanceBefore -
                    Number(
                        paymentData.amount
                    );

                setPaymentData(null);
                setBackendUrl("");

                const message =
                    `₹${formatMoney(
                        paymentData.amount
                    )} paid successfully.\n\n` +
                    `Remaining balance: ₹${formatMoney(
                        remainingBalance
                    )}`;

                if (
                    Platform.OS === "web"
                ) {
                    window.alert(message);

                    navigation.navigate(
                        "Bills"
                    );
                } else {
                    Alert.alert(
                        "Payment Successful",
                        message,
                        [
                            {
                                text:
                                    "View Bills",

                                onPress: () =>
                                    navigation.navigate(
                                        "Bills"
                                    ),
                            },

                            {
                                text: "Home",

                                onPress: () =>
                                    navigation.navigate(
                                        "Home"
                                    ),
                            },
                        ]
                    );
                }
            } catch (error) {
                console.error(
                    "Payment error:",
                    error
                );

                if (deducted) {
                    try {
                        const paymentResponse =
                            await fetch(
                                `${backendUrl}/api/payments/${paymentData.paymentId}`
                            );

                        const serverPayment =
                            await paymentResponse.json();

                        if (
                            serverPayment.status !==
                            "PAID"
                        ) {
                            await saveWalletBalance(
                                balanceBefore
                            );
                        }
                    } catch {
                        await saveWalletBalance(
                            balanceBefore
                        );
                    }
                }

                showMessage(
                    "Payment Failed",
                    error.message ||
                        "The payment could not be completed."
                );
            } finally {
                setIsPaying(false);
            }
        };

    const startPayment = () => {
        if (
            !paymentData ||
            isPaying
        ) {
            return;
        }

        const amount = Number(
            paymentData.amount
        );

        const shopName =
            paymentData.merchant
                ?.merchantName ||
            "the shop";

        if (Platform.OS === "web") {
            const confirmed =
                window.confirm(
                    `Pay ₹${formatMoney(
                        amount
                    )} to ${shopName}?`
                );

            if (confirmed) {
                completePayment();
            }

            return;
        }

        Alert.alert(
            "Confirm Payment",
            `Pay ₹${formatMoney(
                amount
            )} to ${shopName}?`,
            [
                {
                    text: "Cancel",
                    style: "cancel",
                },

                {
                    text: "Pay",
                    onPress:
                        completePayment,
                },
            ]
        );
    };

    if (showCamera) {
        return (
            <View
                style={
                    styles.cameraContainer
                }
            >
                <CameraView
                    style={styles.camera}
                    facing="back"
                    barcodeScannerSettings={{
                        barcodeTypes: [
                            "qr",
                        ],
                    }}
                    onBarcodeScanned={
                        isScanning
                            ? undefined
                            : handleBarcodeScanned
                    }
                />

                <View
                    style={
                        styles.cameraOverlay
                    }
                >
                    <Text
                        style={
                            styles.cameraTitle
                        }
                    >
                        Scan Payment QR
                    </Text>

                    <Text
                        style={
                            styles.cameraDescription
                        }
                    >
                        Place the QR code
                        inside the frame
                    </Text>

                    <View
                        style={
                            styles.scanFrame
                        }
                    />

                    <TouchableOpacity
                        style={
                            styles.cancelButton
                        }
                        onPress={() =>
                            setShowCamera(false)
                        }
                    >
                        <Text
                            style={
                                styles.cancelButtonText
                            }
                        >
                            Cancel
                        </Text>
                    </TouchableOpacity>
                </View>
            </View>
        );
    }

    return (
        <SafeAreaView
            style={styles.container}
        >
            <ScrollView
                contentContainerStyle={
                    styles.content
                }
                showsVerticalScrollIndicator={
                    false
                }
            >
                <Text
                    style={styles.pageTitle}
                >
                    Scan & Pay
                </Text>

                {!paymentData ? (
                    <View
                        style={
                            styles.scanCard
                        }
                    >
                        <View
                            style={
                                styles.scanIcon
                            }
                        >
                            <Text
                                style={
                                    styles.scanIconText
                                }
                            >
                                QR
                            </Text>
                        </View>

                        <Text
                            style={
                                styles.scanTitle
                            }
                        >
                            Choose QR Method
                        </Text>

                        <Text
                            style={
                                styles.scanText
                            }
                        >
                            Scan the shop QR
                            using the camera or
                            upload a QR image.
                        </Text>

                        <TouchableOpacity
                            style={
                                styles.primaryButton
                            }
                            onPress={
                                openCamera
                            }
                            disabled={
                                isLoadingPayment
                            }
                        >
                            <Text
                                style={
                                    styles.primaryButtonText
                                }
                            >
                                Open Camera
                            </Text>
                        </TouchableOpacity>

                        <TouchableOpacity
                            style={
                                styles.secondaryButton
                            }
                            onPress={
                                uploadQRImage
                            }
                            disabled={
                                isLoadingPayment
                            }
                        >
                            <Text
                                style={
                                    styles.secondaryButtonText
                                }
                            >
                                Upload QR Image
                            </Text>
                        </TouchableOpacity>

                        {isLoadingPayment && (
                            <View
                                style={
                                    styles.loadingBox
                                }
                            >
                                <ActivityIndicator
                                    size="large"
                                    color="#2563eb"
                                />

                                <Text
                                    style={
                                        styles.loadingText
                                    }
                                >
                                    Loading payment...
                                </Text>
                            </View>
                        )}
                    </View>
                ) : (
                    <View
                        style={
                            styles.paymentCard
                        }
                    >
                        <View
                            style={
                                styles.shopIcon
                            }
                        >
                            <Text
                                style={
                                    styles.shopIconText
                                }
                            >
                                {paymentData.merchant
                                    ?.merchantName
                                    ?.charAt(0)
                                    ?.toUpperCase() ||
                                    "S"}
                            </Text>
                        </View>

                        <Text
                            style={
                                styles.shopName
                            }
                        >
                            {paymentData.merchant
                                ?.merchantName ||
                                "Unknown Shop"}
                        </Text>

                        <View
                            style={
                                styles.verifiedBadge
                            }
                        >
                            <Text
                                style={
                                    styles.verifiedText
                                }
                            >
                                Verified Merchant ✓
                            </Text>
                        </View>

                        <Text
                            style={
                                styles.amountLabel
                            }
                        >
                            Amount to pay
                        </Text>

                        <Text
                            style={
                                styles.paymentAmount
                            }
                        >
                            ₹
                            {formatMoney(
                                paymentData.amount
                            )}
                        </Text>

                        <TouchableOpacity
                            style={[
                                styles.payButton,
                                isPaying &&
                                    styles.disabledButton,
                            ]}
                            onPress={
                                startPayment
                            }
                            disabled={
                                isPaying
                            }
                        >
                            <Text
                                style={
                                    styles.payButtonText
                                }
                            >
                                {isPaying
                                    ? "Processing..."
                                    : `Pay ₹${formatMoney(
                                          paymentData.amount
                                      )}`}
                            </Text>
                        </TouchableOpacity>

                        <TouchableOpacity
                            style={
                                styles.scanAgainButton
                            }
                            onPress={() => {
                                setPaymentData(
                                    null
                                );

                                setBackendUrl(
                                    ""
                                );
                            }}
                            disabled={
                                isPaying
                            }
                        >
                            <Text
                                style={
                                    styles.scanAgainText
                                }
                            >
                                Scan Another QR
                            </Text>
                        </TouchableOpacity>

                        <Text
                            style={
                                styles.secureText
                            }
                        >
                            Secure payment powered
                            by BillPay
                        </Text>
                    </View>
                )}
            </ScrollView>
        </SafeAreaView>
    );
}

export default ScanScreen;
const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f6f6f7",
    },

    content: {
        width: "100%",
        maxWidth: 560,
        alignSelf: "center",
        paddingHorizontal: 22,
        paddingTop: 24,
        paddingBottom: 48,
    },

    pageTitle: {
        marginTop: 10,
        marginBottom: 22,
        color: "#18181b",
        fontSize: 30,
        fontWeight: "900",
        letterSpacing: -0.7,
    },

    scanCard: {
        padding: 26,
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#e5e5e5",
        borderRadius: 18,
        backgroundColor: "#ffffff",

        elevation: 2,

        shadowColor: "#000000",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.05,
        shadowRadius: 10,
    },

    scanIcon: {
        width: 78,
        height: 78,
        marginBottom: 18,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: "#fecaca",
        borderRadius: 20,
        backgroundColor: "#fff1f2",
    },

    scanIconText: {
        color: "#dc2626",
        fontSize: 24,
        fontWeight: "900",
    },

    scanTitle: {
        marginBottom: 7,
        color: "#18181b",
        fontSize: 20,
        fontWeight: "900",
        letterSpacing: -0.2,
    },

    scanText: {
        maxWidth: 360,
        marginBottom: 14,
        color: "#71717a",
        fontSize: 13,
        lineHeight: 20,
        textAlign: "center",
    },

    primaryButton: {
        width: "100%",
        minHeight: 50,
        marginTop: 13,
        paddingHorizontal: 18,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 12,
        backgroundColor: "#dc2626",

        elevation: 1,

        shadowColor: "#dc2626",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.12,
        shadowRadius: 8,
    },

    primaryButtonText: {
        color: "#ffffff",
        fontSize: 15,
        fontWeight: "900",
    },

    secondaryButton: {
        width: "100%",
        minHeight: 50,
        marginTop: 12,
        paddingHorizontal: 18,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: "#fecaca",
        borderRadius: 12,
        backgroundColor: "#fffafa",
    },

    secondaryButtonText: {
        color: "#dc2626",
        fontSize: 15,
        fontWeight: "800",
    },

    loadingBox: {
        marginTop: 24,
        alignItems: "center",
    },

    loadingText: {
        marginTop: 10,
        color: "#71717a",
        fontSize: 13,
        textAlign: "center",
    },

    paymentCard: {
        padding: 28,
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#e5e5e5",
        borderRadius: 20,
        backgroundColor: "#ffffff",

        elevation: 2,

        shadowColor: "#000000",
        shadowOffset: {
            width: 0,
            height: 5,
        },
        shadowOpacity: 0.06,
        shadowRadius: 12,
    },

    shopIcon: {
        width: 78,
        height: 78,
        marginBottom: 17,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: "#fecaca",
        borderRadius: 39,
        backgroundColor: "#fff1f2",
    },

    shopIconText: {
        color: "#dc2626",
        fontSize: 31,
        fontWeight: "900",
    },

    shopName: {
        color: "#18181b",
        fontSize: 22,
        fontWeight: "900",
        letterSpacing: -0.4,
        textAlign: "center",
    },

    verifiedBadge: {
        marginTop: 9,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderWidth: 1,
        borderColor: "#bbf7d0",
        borderRadius: 999,
        backgroundColor: "#f0fdf4",
    },

    verifiedText: {
        color: "#15803d",
        fontSize: 11,
        fontWeight: "800",
    },

    amountLabel: {
        marginTop: 28,
        color: "#71717a",
        fontSize: 12,
        fontWeight: "700",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },

    paymentAmount: {
        marginTop: 7,
        marginBottom: 26,
        color: "#18181b",
        fontSize: 42,
        fontWeight: "900",
        letterSpacing: -1,
    },

    payButton: {
        width: "100%",
        minHeight: 52,
        paddingHorizontal: 18,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 12,
        backgroundColor: "#dc2626",

        elevation: 1,

        shadowColor: "#dc2626",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.14,
        shadowRadius: 8,
    },

    payButtonText: {
        color: "#ffffff",
        fontSize: 16,
        fontWeight: "900",
    },

    scanAgainButton: {
        width: "100%",
        minHeight: 50,
        marginTop: 12,
        paddingHorizontal: 18,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: "#e5e5e5",
        borderRadius: 12,
        backgroundColor: "#fafafa",
    },

    scanAgainText: {
        color: "#18181b",
        fontSize: 14,
        fontWeight: "800",
    },

    secureText: {
        marginTop: 18,
        color: "#a1a1aa",
        fontSize: 11,
        lineHeight: 17,
        textAlign: "center",
    },

    disabledButton: {
        opacity: 0.5,
    },

    cameraContainer: {
        flex: 1,
        backgroundColor: "#000000",
    },

    camera: {
        flex: 1,
    },

    cameraOverlay: {
        ...StyleSheet.absoluteFillObject,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(0, 0, 0, 0.38)",
    },

    cameraTitle: {
        position: "absolute",
        top: 68,
        color: "#ffffff",
        fontSize: 24,
        fontWeight: "900",
        letterSpacing: -0.4,
    },

    cameraDescription: {
        position: "absolute",
        top: 106,
        maxWidth: 320,
        color: "#e4e4e7",
        fontSize: 13,
        lineHeight: 19,
        textAlign: "center",
    },

    scanFrame: {
        width: 250,
        height: 250,
        borderWidth: 3,
        borderColor: "#ffffff",
        borderRadius: 22,
        backgroundColor: "transparent",

        shadowColor: "#dc2626",
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0.35,
        shadowRadius: 14,
    },

    cancelButton: {
        position: "absolute",
        bottom: 50,
        minWidth: 150,
        paddingHorizontal: 28,
        paddingVertical: 13,
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#ffffff",
        borderRadius: 12,
        backgroundColor: "#ffffff",
    },

    cancelButtonText: {
        color: "#18181b",
        fontSize: 14,
        fontWeight: "900",
    },
});